Models/ErrorViewModel.cs
namespace EventoApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/EventosModel.cs
using System.ComponentModel.DataAnnotations;

namespace EventoApplication.Models
{
    public class EventosModel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do Contratante!")]
        public string Contratante { get; set; }

        [Required(ErrorMessage = "Digite o nome da Empresa!")]
        public string Empresa { get; set; }

        [Required(ErrorMessage = "Digite o nome do Evento!")]
        public string Nome { get; set; }

        public DateTime dataUltimaAtualizacao { get; set; } = DateTime.Now;

    }
}

Controllers/EventoController.cs
using ClosedXML.Excel;
using EventoApplication.Data;
using EventoApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace EventoApplication.Controllers
{
    public class EventoController : Controller
    {
        readonly private ApplicationDbContext _db;

        public EventoController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<EventosModel> eventos = _db.Eventos;
            return View(eventos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EventosModel evento = _db.Eventos.FirstOrDefault(x => x.Id == id);

            if (evento == null) 
            {
                return NotFound();
            }

            return View(evento);
        }

        [HttpGet]
        public IActionResult Excluir(int? id) 
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EventosModel evento = _db.Eventos.FirstOrDefault(x => x.Id == id);

            if (evento == null)
            {
                return NotFound();
            }
            return View(evento);
        }

        public IActionResult Exportar()
        {
            var dados = GetDados();
            using (XLWorkbook workBook = new XLWorkbook())
            {
                workBook.AddWorksheet(dados, "Dados Eventos");
                using (MemoryStream ms = new MemoryStream())
                {
                    workBook.SaveAs(ms);
                    return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Evento.xls");
                }

            }
        }

        private DataTable GetDados()
        {
            DataTable dataTable = new DataTable();

            dataTable.TableName = "Dados eventos";

            dataTable.Columns.Add("Contratante", typeof(string));
            dataTable.Columns.Add("Empresa", typeof(string));
            dataTable.Columns.Add("Nome do evento", typeof(string));
            dataTable.Columns.Add("Data do evento", typeof(DateTime));

            var dados = _db.Eventos.ToList();

            if (dados.Count > 0)
            {
                dados.ForEach(evento =>
                {
                    dataTable.Rows.Add(evento.Contratante, evento.Empresa, evento.Nome, evento.dataUltimaAtualizacao);
                });
            }

                return dataTable;
        }

        [HttpPost]
        public IActionResult Cadastrar(EventosModel eventos)
        {
            if (ModelState.IsValid)
            {
                _db.Eventos.Add(eventos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Editar(EventosModel evento)
        {
            if (ModelState.IsValid)
            {
                var eventoDB = _db.Eventos.Find(evento.Id);

                eventoDB.Contratante = evento.Contratante;
                eventoDB.Empresa = evento.Empresa;
                eventoDB.Nome = evento.Nome;

                _db.Eventos.Update(eventoDB);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizada com sucesso!";

                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Erro ao realizar edição!";

            return View(evento);
        }


        [HttpPost]
        public IActionResult Excluir(EventosModel evento)
        {
            if(evento == null)
            {
                return NotFound();
            }
            _db.Eventos.Remove(evento);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Exclusão realizada com sucesso!";

            return RedirectToAction("Index");

        }


    }
}

Controllers/HomeController.cs
using EventoApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EventoApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Evento/Cadastrar.cshtml
@model EventosModel

@{
    ViewData["title"] = "Cadastrar Evento";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de Eventos</h1>
    </div>
    
    <form method="post" asp-controller="Evento" asp-action="Cadastrar">
        <div class="mb-3">
            <label for="Contratante" class="text-light form-label">Contratante:</label>
            <input type="text" asp-for="Contratante" class="form-control text-light" placeholder="Quem está contratando o serviço?">
            <span class="text-danger" asp-validation-for="Contratante"></span>
        </div>
        <div class="mb-3">
            <label for="Empresa" class="text-light form-label">Empresa:</label>
            <input asp-for="Empresa" type="text" class="form-control text-light" placeholder="Quem está oferecendo o serviço?">
            <span class="text-danger" asp-validation-for="Empresa"></span>
        </div>
        <div class="mb-3">
            <label class="text-light form-label" for="Nome">Evento:</label>
            <input type="text" asp-for="Nome" class="form-control text-light" placeholder="Qual o nome do evento?">
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Evento" asp-action="Index">Voltar</a>
        </div>
    </form>
    
</div>

Views/Evento/Editar.cshtml
@model EventosModel
@{
    ViewData["title"] = "Editar Evento";
}


<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de Eventos</h1>
    </div>

    <form method="post" asp-controller="Evento" asp-action="Editar">
        <input type="hidden" asp-for=Id />

        <div class="mb-3">
            <label for="Contratante" class="text-light form-label">Contratante:</label>
            <input type="text" asp-for="Contratante" class="form-control text-light" placeholder="Quem está contratando o serviço?">
            <span class="text-danger" asp-validation-for="Contratante"></span>
        </div>
        <div class="mb-3">
            <label for="Empresa" class="text-light form-label">Empresa:</label>
            <input asp-for="Empresa" type="text" class="form-control text-light" placeholder="Quem está oferecendo o serviço?">
            <span class="text-danger" asp-validation-for="Empresa"></span>
        </div>
        <div class="mb-3">
            <label class="text-light form-label" for="Nome">Evento:</label>
            <input type="text" asp-for="Nome" class="form-control text-light" placeholder="Qual o nome do evento?">
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Evento" asp-action="Index">Voltar</a>
        </div>
    </form>

</div>

Views/Evento/Excluir.cshtml
@model EventosModel

@{
    ViewData["title"] = "Excluir Evento";
}


<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Exclusão de Eventos</h1>
    </div>

    <form method="post" asp-controller="Evento" asp-action="Excluir">
        <input type="hidden" asp-for=Id />

        <h2 class="text-light">Tem certeza que deseja excluir o registro?</h2>

        <div class="mb-3">
            <label for="Contratante" class="text-light form-label">Contratante:</label>
            <input type="text" asp-for="Contratante" class="form-control text-light" placeholder="Quem está contratando o serviço?" disabled>
            <span class="text-danger" asp-validation-for="Contratante"></span>
        </div>
        <div class="mb-3">
            <label for="Empresa" class="text-light form-label">Empresa:</label>
            <input asp-for="Empresa" type="text" class="form-control text-light" placeholder="Quem está oferecendo o serviço?" disabled>
            <span class="text-danger" asp-validation-for="Empresa"></span>
        </div>
        <div class="mb-3">
            <label class="text-light form-label" for="Nome">Evento:</label>
            <input type="text" asp-for="Nome" class="form-control text-light" placeholder="Qual o nome do evento?" disabled>
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Evento" asp-action="Index">Voltar</a>
        </div>
    </form>

</div>

Views/Evento/Index.cshtml
@model IEnumerable<EventosModel>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Eventos</h1>
        
        <div>
            <a class="btn btn-success mx-2" asp-controller="Evento" asp-action="Exportar"><i class="bi bi-file-earmark-plus mx-2"></i>Exportar</a>
            <a class="btn btn-success mx-2" asp-controller="Evento" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus mx-2"></i>Cadastrar novo evento</a>
        </div>
    </div>

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }


<table id="Eventos" class="table table-light table-hover mt-5">
    <thead>
        <tr>
            <th scope="col">Contratante</th>
            <th scope="col">Empresa</th>
            <th scope="col">Evento</th>
            <th scope="col">Última Atualização</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @if(Model != null)
        {
            @foreach(var evento in Model)
            {
                <tr>
                    <th scope="row">@evento.Contratante</th>
                    <td>@evento.Empresa</td>
                    <td>@evento.Nome</td>
                    <td>@evento.dataUltimaAtualizacao</td>
                    <td>
                            <a asp-controller="Evento" asp-action="Editar" asp-route-id="@evento.Id" class="btn btn-warning mx-2"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            <a asp-controller="Evento" asp-action="Excluir" asp-route-id="@evento.Id" class="btn btn-danger mx-2"><i class="bi bi-trash mx-2"></i>Excluir</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Eventos</h1>
    <p>Cadastre, edite e exclua eventos!</p>
    <div>
        <img src="/img/image.png"/>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eventos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventoApplication.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Eventos Tech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Evento" asp-action="Index"><i class="bi bi-calendar-event mx-2"></i>Eventos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2024 - EventoApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>